### ISSUE TITLE
https instead of http in meta links

### ISSUE THREAD

**Issue by krisgardiner** [Say-Their-Name/say-their-names-web#107]
FILL OUT THE FORM BELOW OR THE ISSUE WILL BE AUTO-CLOSED

**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Documentation
- [ ] Technical Discussion

**Description (Please type a clear and concise description below)** 
- Meta links to saytheirnames.io should have `https` instead of http`
- Meta can be found in `src/components/common/Seo.js`

**Comment by Easybuoy** [comment]
You've got great eyes for finding these things, nice catch 👍🏽

**Comment by Easybuoy** [comment]
Fixed in #110
