### ISSUE TITLE
Bug: tab empty states appear to client

### ISSUE THREAD

**Issue by ashleygraf101** [Say-Their-Name/say-their-names-web#114]
FILL OUT THE FORM BELOW OR THE ISSUE WILL BE AUTO-CLOSED

**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Documentation
- [ ] Technical Discussion

**Description (Please type a clear and concise description below)** 

Include text that says something like "Coming Soon" in donations & petitions tabs where we are still filling in the initial list.

**Comment by Easybuoy** [comment]
I think if any donation or petition is still been worked on, it should not be shown on the client

**Comment by ashleygraf101** [comment]
Ok, that's a better way to do it.
