### ISSUE TITLE
Pagination Support (Donation & Petititions)

### ISSUE THREAD

**Issue by Easybuoy** [Say-Their-Name/say-their-names-web#126]
FILL OUT THE FORM BELOW OR THE ISSUE WILL BE AUTO-CLOSED

**Issue Type (check one)**

- [ ] Bug Report
- [x] Feature Idea
- [ ] Documentation
- [ ] Technical Discussion

**Description (Please type a clear and concise description below)** 
We need to have pagination on the Donation and Petition pages just like we have on the Home page.

**Comment by samakintunde37** [comment]
Closing this since the it's been merged.
