### ISSUE TITLE
Donations Failing Tests

### ISSUE THREAD

**Issue by Easybuoy** [Say-Their-Name/say-their-names-web#129]
FILL OUT THE FORM BELOW OR THE ISSUE WILL BE AUTO-CLOSED

**Issue Type (check one)**

- [ ] Bug Report
- [ ] Feature Idea
- [ ] Documentation
- [ ] Technical Discussion
- [x] Tests

**Description (Please type a clear and concise description below)** 
The tests were failing after implementing #127, so I commented them so as to be able to push and merge, as the feature was MVP critical.

Tests can be found at `./pages/Donations.test.js`

**Comment by krisgardiner** [comment]
Will take a look!

**Comment by krisgardiner** [comment]
Fix is here https://github.com/Say-Their-Name/say-their-names-web/pull/133
