### ISSUE TITLE
Fix link to the Google  Play Store

### ISSUE THREAD

**Issue by vinny2020** [Say-Their-Name/say-their-names-web#157]
FILL OUT THE FORM BELOW OR THE ISSUE WILL BE AUTO-CLOSED

**Issue Type (check one)**

- [ X ] Bug Report
- [ ] Feature Idea
- [ ] Documentation
- [ ] Technical Discussion

**Description (Please type a clear and concise description below)** 
The Play Store link to the android app is missing. the url is:
https://play.google.com/store/apps/details?id=io.saytheirnames.android

**Comment by Easybuoy** [comment]
Fixed in #152
