### ISSUE TITLE
Husky Configuration Setup

### ISSUE THREAD

**Issue by Easybuoy** [Say-Their-Name/say-their-names-web#18]
FILL OUT THE FORM BELOW OR THE ISSUE WILL BE AUTO-CLOSED

**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion

**Description (Please type a clear and concise description below)** 
- Husky doesn't seem to be running currently before a commit is made, looks like the configuration's not setup properly

**Comment by DanFerrer** [comment]
Taking a look tonight, looks like the package ```lint-staged``` has something to do with it

**Comment by iamcristos** [comment]
is someone currently working on this? if not I can pick it up

**Comment by DanFerrer** [comment]
@iamcristos dealing with some stuff right now and cant get to this, so feel free to take it 🙏 . I saw that prettier wasn't installed locally so that might also be part of the problem.
