### ISSUE TITLE
Implement caching and loader to improve website speed and user experience.

### ISSUE THREAD

**Issue by samakintunde37** [Say-Their-Name/say-their-names-web#40]
**Issue Type (check one)**

- [ ] Bug Report
- [x] Feature Idea
- [ ] Technical Discussion

**Description (Please type a clear and concise description below)** 
On use of the website's pagination(implemented in #26) on the homepage, the data for each victim of each page is always refetched. The images are however being cached because they're being served from a CDN which is great. The victims' data request takes a while and there's currently no loader which isn't a great experience.

I've done a bit of research and the best options for this are Vercel's [SWR](https://swr.now.sh/) package and [React Query](https://github.com/tannerlinsley/react-query). I haven't used either before but SWR is from a big company and React Query is also very popular and seems to solve some issues with SWR. We should also add a loader to communicate the loading state.

I'd like to hear your thoughts on the decision we take. @Say-Their-Name/web

**Comment by joedemcher** [comment]
Hey, did you want some help with this?

**Comment by samakintunde37** [comment]
That'd be appreciated. I've pretty much got it up to a good point. It's just the way useSWR works which I'm trying to wrap my head around.
I'll push what I've got soon and we can reason about that?
