### ISSUE TITLE
404 page needs to completely replace the contents of Donation and Petition pages

### ISSUE THREAD

**Issue by jdshaeffer** [Say-Their-Name/say-their-names-web#58]
FILL OUT THE FORM BELOW OR THE ISSUE WILL BE AUTO-CLOSED

**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion

**Description (Please type a clear and concise description below)** 

The error page should replace all contents of the Donation and Petition pages if no donations/petitions are present. Currently you can still see the default content (when nothing is available) along with the 404 page. Don't know if this is by design but I don't think it looks that great. I'm going to open a new PR soon that covers the 'No Petitions Found' similar to the Donations page (along with implementing the Tabs component), so don't worry about doing that.

The error page might also be catching too much. Once it popped up the 404 message and still proceeded to display all the donations.

**Comment by Easybuoy** [comment]
Great catch, I think I know where the issue might be coming from, let me know if you need any help @jdshaeffer

**Comment by kndri** [comment]
Just checking in -- is this still an issue?

**Comment by Easybuoy** [comment]
This has been fixed
