### ISSUE TITLE
Bug: #saytheirnames-{full_name} hashtag

### ISSUE THREAD

**Issue by ashleygraf101** [Say-Their-Name/say-their-names-web#62]
**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion

**Description (Please type a clear and concise description below)** 

#saytheirnames-{full_name} doesn’t form a hashtag according to Twitter spec. It creates a list of tweets which have both #saytheirnames and #{full_name}. For example see https://twitter.com/search?q=%23saytheirnames-KumanjayiWalker. 

![image](https://user-images.githubusercontent.com/7345609/83971977-336cba80-a921-11ea-8946-a30a3d933eb5.png)
![image](https://user-images.githubusercontent.com/7345609/83971987-4089a980-a921-11ea-9faa-48d3147b58d6.png)

**Comment by Easybuoy** [comment]
Thanks for this @ashleygraf101, we were thinking of drafting different contents for the share links, can you help with that?

**Comment by ashleygraf101** [comment]
@Easybuoy I can help with that.

**Comment by Easybuoy** [comment]
Any update on this? @ashleygraf101

**Comment by ashleygraf101** [comment]
For the share links are you referring both to the social media hashtags and the share to twitter/fb/whatapp section?

**Comment by Easybuoy** [comment]
> For the share links are you referring both to the social media hashtags and the share to twitter/fb/whatapp section?

Just the twitter/fb/whatsapp section for both the petition and donation pages

**Comment by ashleygraf101** [comment]
Will have something for you in 15 - currently working on petition page share to copy.

**Comment by ashleygraf101** [comment]
**Victim’s Donation**

Join me in donating to {full_name}’s fund, and supporting his family’s fight for justice. #SayTheirNames #BlackLivesMatter #{#full_name} https://saytheirnames.io/donate/donate-to-{full_name} 

**Victim’s Petition**

Help bring justice to {full_name} by signing this petition and put pressure on the authorities to do the right thing. If we show up in numbers, we can win. #SayTheirNames #BlackLivesMatter #{full_name} 
https://saytheirnames.io/sign/petition-for-{full_name}

**Movement Donation**

The movement goes on. Join me in supporting {fund} and let’s help fuel the campaign for justice together.  #BlackLivesMatter #SayTheirNames https://saytheirname.netlify.app/donate/{fund} 

**Protestors Donation**

Support your _PLEASE INSERT WORD HERE ALONG THE LINES OF COMPATRIOTS_ on the front line by donating to {fund} and help keep the pressure on in our fight to end police brutality.  #BlackLivesMatter #SayTheirNames https://saytheirname.netlify.app/donate/{fund}

**Comment by lantelyes** [comment]
Is this task up for grabs? Id love to tackle it!

**Comment by lantelyes** [comment]
ok, im going to start work on it!

**Comment by lantelyes** [comment]
So to clarify the scope of this ticket @Easybuoy, it is to replace the text used when clicking the sharing links on the various pension and donation pages?

**Comment by Easybuoy** [comment]
Yes it is @lantelyes

**Comment by lantelyes** [comment]
Almost done! Just had two questions:

1) I see a section under pensions for policy, do we have any copy for that?
2) The protestors donation list seems to be empty, so I'm not sure how I can test that part, is there any way we can populate the database with some people?

**Comment by ashleygraf101** [comment]
1. Writing that now. I'll have something for you in 15.

**Comment by ashleygraf101** [comment]
**Policy Petition**

Sign this petition to show support for policy change and bring media attention to the number of people who want action. #BlackLivesMatter #SayTheirNames 
https://saytheirname.netlify.app/sign/{petition}

**Comment by ashleygraf101** [comment]
@lantelyes How are you going with this?

**Comment by lantelyes** [comment]
I am basically done, I am just unable to test the protestor donation copy as there are none in the database currently

**Comment by ashleygraf101** [comment]
@devingray manages data.

**Comment by lantelyes** [comment]
Great, I have everything else done, I just need that data to test this last part @devingray

**Comment by Easybuoy** [comment]
Any update on this? @lantelyes

**Comment by lantelyes** [comment]
I am blocked by some missing data and I have posted in the data channel in slack.

@devingray said we would ping me when it's in, I will follow up now

**Comment by Easybuoy** [comment]
Okay, can you create a draft pull request so we can test the others

**Comment by lantelyes** [comment]
sure! let me do that now
