### ISSUE TITLE
Misspelling on About page banner

### ISSUE THREAD

**Issue by ashleygraf101** [Say-Their-Name/say-their-names-web#63]
**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion

**Description (Please type a clear and concise description below)** 

![image](https://user-images.githubusercontent.com/7345609/83972187-1be20180-a922-11ea-8c96-599604bf8605.png)

**Comment by Easybuoy** [comment]
This has been updated on the design, download the banner and replace in code.

Link to design: https://www.figma.com/file/AUlfUejB2SVF8ZHSzxne7O/STNS?node-id=1212%3A1911
