### ISSUE TITLE
Copy comments: Victim’s donations

### ISSUE THREAD

**Issue by ashleygraf101** [Say-Their-Name/say-their-names-web#64]
FILL OUT THE FORM BELOW OR THE ISSUE WILL BE AUTO-CLOSED

**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion

**Description (Please type a clear and concise description below)** 

Victim's donation funds have petition copy. They would perhaps be more user friendly with a short description of the purpose of the fund. 

Example below of current output. 

![image](https://user-images.githubusercontent.com/7345609/83972271-82ffb600-a922-11ea-8f61-43efd5db0190.png)

**Comment by Easybuoy** [comment]
cc @devingray

**Comment by devingray** [comment]
Got it, fixed, when we have more hands in #data we will update this
