### ISSUE TITLE
Profile back button only navigates to page 1

### ISSUE THREAD

**Issue by charlyecastro** [Say-Their-Name/say-their-names-web#67]
FILL OUT THE FORM BELOW OR THE ISSUE WILL BE AUTO-CLOSED

**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion

**Description (Please type a clear and concise description below)** 

I believe it would be better for the user experience if the back button returns you to the specific page number you recently visited instead of the first page.

The gif below shows me visiting a profile on page 6 and when I hit the **Back To Profiles** button, the site navigates to me to page 1 instead of page 6. 

![2020-06-07 10 04 54](https://user-images.githubusercontent.com/24886389/83975073-8f462d80-a8a6-11ea-94d4-dc6a8ff213c9.gif)

**Comment by samakintunde37** [comment]
I noticed this too but I was busy working on another issue.
If there's no one taking this, I can get started on it. Fine?

**Comment by lantelyes** [comment]
I can take this!

**Comment by kouamendri** [comment]
@lantelyes I think you are in the clear to take this one. Sam is in a different time zone, so right now it is 2AM where he is located.

**Comment by samakintunde37** [comment]
@lantelyes I finished the other issue but yeah go ahead, if you want to.

**Comment by Easybuoy** [comment]
Fixed in #76
