### ISSUE TITLE
Donations tabs is not responsive

### ISSUE THREAD

**Issue by charlyecastro** [Say-Their-Name/say-their-names-web#82]
FILL OUT THE FORM BELOW OR THE ISSUE WILL BE AUTO-CLOSED

**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion

**Description (Please type a clear and concise description below)** 

When on my phone or when I resize the window to a mobile view, the donations tabs don't fit on the screen. As you can see from the gif below, the tabs overextend making the users have to scroll from left to right.

![2020-06-08 15 29 27](https://user-images.githubusercontent.com/24886389/84086556-03fb9380-a99d-11ea-8ada-53b15a787bad.gif)

**Comment by Easybuoy** [comment]
Working on this

**Comment by charlyecastro** [comment]
Would the best solution be adding media queries to the tabs and resize them based on the window size?

**Comment by Easybuoy** [comment]
> Would the best solution be adding media queries to the tabs and resize them based on the window size?

Yes, that’s what I did. Was working on a task and saw it, so i decided to fix it

**Comment by charlyecastro** [comment]
Sounds good! Thanks @Easybuoy
