### ISSUE TITLE
Slack and Trello Invite LInks aren't working

### ISSUE THREAD

**Issue by caelinsutch** [Say-Their-Name/say-their-names-web#83]
FILL OUT THE FORM BELOW OR THE ISSUE WILL BE AUTO-CLOSED

**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion

**Description (Please type a clear and concise description below)** 

Clicking on the links to Slack and Trello in the `Contributing.md` file don't go anywhere (dead links)

**Comment by daniellimhong** [comment]
Hello @caelinsutch! 

I was the one to update the links as I was having trouble with the links prior. If possible, can you screenshot what you’re seeing when you press on the links? I’ve tested the links just now and it’s redirecting me to correct pages. Thank you!

**Comment by caelinsutch** [comment]
After testing again a few times in incognito windows, it does seem to work. Must've been an internet or server problem :(

Thanks for the help!
