### ISSUE TITLE
Add Description and Website to Github Repo

### ISSUE THREAD

**Issue by caelinsutch** [Say-Their-Name/say-their-names-web#85]
Description and website should be on top of the repo. There's no way to see the current release of the website. 

**Issue Type (check one)**

- [ ] Bug Report
- [x] Feature Idea
- [ ] Technical Discussion

**Comment by samakintunde37** [comment]
@Easybuoy @kndri This is pretty useful. Is this something you guys can sort out?

**Comment by kndri** [comment]
It is indeed! The site is not live, we are doing a MVP launch in the next couple of days. When it goes live, information would be update. 

Thanks for brining it up! @samakintunde37 @caelinsutch

**Comment by kndri** [comment]
done!
