### ISSUE TITLE
Revise Analytics Tag

### ISSUE THREAD

**Issue by cdemeke** [Say-Their-Name/say-their-names-web#92]
Our previous analytics was set up to point to "http://say-their-names.com" however since we will be on "http://saytheirnames.io/" we should use the following analytics tag.

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-0P757MTVT6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-0P757MTVT6');
</script>
```

**Comment by kndri** [comment]
@cdemeke is this the official one, like created from the saytheirnames.io GA account?

**Comment by Easybuoy** [comment]
So there were still some debates as to which analytics we would be using. There were concerns about privacy

**Comment by kndri** [comment]
> So there were still some debates as to which analytics we would be using. There were concerns about privacy

I opened up and the floor for the people with concerns to provide an alternative, no one stepped up.

**Comment by cdemeke** [comment]
I'd originally created an analytics account using my personal Gmail account, do we have a saytheirnames gmail account? Happy to swap it out for that or create the gmail account if one doesn't exist.

**Comment by kndri** [comment]
cc: @devingray

**Comment by Easybuoy** [comment]
> nalytics account using my personal Gm

Yes, we have a gmail account

**Comment by Easybuoy** [comment]
I have gotten the google tag id, what's just needed it to add it to the environment variables of the application. I'd do that

**Comment by kndri** [comment]
Up and running!
