### ISSUE TITLE
Bug: New SEO code isn't picked up by Twitter or FB. 

### ISSUE THREAD

**Issue by ashleygraf101** [Say-Their-Name/say-their-names-web#95]
FILL OUT THE FORM BELOW OR THE ISSUE WILL BE AUTO-CLOSED

**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Documentation
- [ ] Technical Discussion

**Description (Please type a clear and concise description below)** 

Neither FB or Twitter appear to be registering anything that doesn't appear in the scraped URL provided by FB.  For example, on pages which aren't the home page, the home page meta description is still showing up, and there is no image in the preview.

![image](https://user-images.githubusercontent.com/7345609/84165448-11a53c00-aab7-11ea-959b-32cbb1fa54f2.png)

https://developers.facebook.com/tools/debug/echo/?q=http%3A%2F%2Fsaytheirnames.io%2Fdonations 

![image](https://user-images.githubusercontent.com/7345609/84165948-a14aea80-aab7-11ea-9145-76449cea4cfd.png)

**Comment by Easybuoy** [comment]
Yes, that's because the app hasn't been indexed yet. I've put up the app for indexing on Google Search Console, so hopefully, it's done soon

**Comment by Easybuoy** [comment]
Still researching on it

**Comment by ashleygraf101** [comment]
Oh right. Huh.

**Comment by Easybuoy** [comment]
Fixed in #96! It works now @ashleygraf101
